/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QLTV.GUI;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import QLTV.BUS.QLNCCBUS;
import QLTV.DAO.QLNCCDAO;
import QLTV.DTO.NHACUNGCAP;

/**
 *
 * @author MSI
 */
public class QLNCCGUI extends javax.swing.JFrame {
    DefaultTableModel defaultTableModel = new DefaultTableModel();
    ArrayList<NHACUNGCAP> ds = new ArrayList<>();
    static ArrayList<NHACUNGCAP> list;

    /**
     * Creates new form GUI
     */
    public QLNCCGUI() throws Exception {
        initComponents();
        list = new QLNCCDAO().getlist();
        NHACUNGCAP a = new NHACUNGCAP("1", "AN");
        ds.add(a);
        NHACUNGCAP b = new NHACUNGCAP("2", "TAM");
        ds.add(b);
        show(list);
    }

    public QLNCCGUI(String x){
        main(null);
    }

    public void show(ArrayList<NHACUNGCAP> dsnxb) {
        Vector<String> header = new Vector<>();
        header.add("id");
        header.add("name");

        defaultTableModel = new DefaultTableModel(header, 0);
        for (NHACUNGCAP ds : dsnxb) {
            Vector<String> row = new Vector<>();
            row.add(ds.getId());
            row.add(ds.getName());
            defaultTableModel.addRow(row);
        }
        jTable1.setModel(defaultTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NXB = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        NAME = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        FIND = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        find = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NXB.setText("NHÀ CUNG CẤP");

        jButton1.setText("THÊM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("NAME");

        NAME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClick(evt);
            }
        });

        jButton2.setText("SỬA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("XÓA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        FIND.setText("TÌM KIẾM");
        FIND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FINDActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null },
                        { null, null },
                        { null, null },
                        { null, null }
                },
                new String[] {
                        "Title 1", "Title 2"
                }));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        find.addMouseListener(new java.awt.event.MouseAdapter() {

        });
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });

        jLabel3.setText("NHẬP ID ĐỂ TÌM KIẾM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(164, 164, 164)
                                                .addComponent(NXB)
                                                .addGap(115, 115, 115))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 136,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(107, 107, 107))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                layout.createSequentialGroup()
                                                                        .addComponent(jButton2)
                                                                        .addGap(109, 109, 109))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButton3)
                                                                .addGap(83, 83, 83))))))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(FIND, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(find))
                                .addContainerGap(73, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(NXB)
                                                .addGap(16, 16, 16)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton2)
                                                .addGap(1, 1, 1)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addComponent(jButton1)
                                                .addGap(5, 5, 5)
                                                .addComponent(jButton3)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70,
                                                        Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(83, 83, 83)
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(find, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(FIND)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        StringBuilder sb = new StringBuilder();
        if (ID.getText().equals("")) {
            sb.append("id không được bỏ trống");
            ID.setBackground(Color.red);
        } else
            ID.setBackground(Color.white);
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        try {
            NHACUNGCAP nxb = new NHACUNGCAP();
            nxb.setId(ID.getText());
            nxb.setName(NAME.getText());
            QLNCCBUS bus = new QLNCCBUS();
            bus.add(nxb);
            JOptionPane.showMessageDialog(this, "them thanh cong vao csdl");
            Vector<String> header = new Vector<>();
            header.add("id");
            header.add("name");

            if (defaultTableModel.getRowCount() == 0) {
                defaultTableModel = new DefaultTableModel(header, 0);
            }

            Vector<String> row = new Vector<>();
            row.add(nxb.getId());
            row.add(nxb.getName());
            defaultTableModel.addRow(row);
            jTable1.setModel(defaultTableModel);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e.getMessage());
            e.printStackTrace();
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    public void FINDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_FINDActionPerformed
        try {
            ArrayList<NHACUNGCAP> nxb = new ArrayList<>();
            QLNCCBUS data = new QLNCCBUS();
            if (find.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "THÔNG TIN TÌM KIẾM ĐANG RỖNG");
                return;
            }
            try {

                nxb.add(data.findid(find.getText()));

                if (data.findid(find.getText()) != null) {
                    show(nxb);
                } else {
                    JOptionPane.showMessageDialog(this, "KHÔNG TÌM THẤY!");
                }

            } catch (Exception ex) {
                Logger.getLogger(QLNCCGUI.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (Exception ex) {
            Logger.getLogger(QLNCCGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // }// GEN-LAST:event_FINDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        try {
            NHACUNGCAP nxb = new NHACUNGCAP();
            nxb.setId(ID.getText());
            nxb.setName(NAME.getText());
            QLNCCBUS data = new QLNCCBUS();
            data.update(nxb);
        } catch (Exception ex) {
            Logger.getLogger(QLNCCGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        int i = jTable1.getSelectedRow();
        if (i >= 0) {
            defaultTableModel.setValueAt(ID.getText(), i, 0);
            defaultTableModel.setValueAt(NAME.getText(), i, 1);

            jTable1.setModel(defaultTableModel);
            JOptionPane.showMessageDialog(this, "update csdl thanh cong");
        }

    }// GEN-LAST:event_jButton2ActionPerformed

    private void jTableMouseClick(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTableMouseClick
    }// GEN-LAST:event_jTableMouseClick

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTable1MouseClicked
        int i = jTable1.getSelectedRow();
        ID.setText(jTable1.getModel().getValueAt(i, 0).toString());
        NAME.setText(jTable1.getModel().getValueAt(i, 1).toString());
    }// GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        QLNCCBUS data = new QLNCCBUS();
        int i = jTable1.getSelectedRow();
        try {
            data.delete(ID.getText());
            JOptionPane.showMessageDialog(this, "xoa thanh cong!");
            defaultTableModel.removeRow(i);
            jTable1.setModel(defaultTableModel);
        } catch (Exception ex) {
            Logger.getLogger(QLNCCGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_jButton3ActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_findActionPerformed
    }// GEN-LAST:event_findActionPerformed

    /**
     * @param args the command line arguments
     */


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNCCGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNCCGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNCCGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNCCGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QLNCCGUI().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(QLNCCGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FIND;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField NAME;
    private javax.swing.JLabel NXB;
    private javax.swing.JTextField find;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
